# Generated by Django 5.1.3 on 2025-05-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
