# Generated by Django 5.1.3 on 2025-05-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_application', '0002_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
