# Generated by Django 5.1.3 on 2025-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_application', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
