# Generated by Django 5.1.3 on 2025-06-07 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_application', '0008_message_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
