# Generated by Django 5.1.3 on 2025-06-07 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_application', '0009_customuser_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contacted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
